### ISSUE TITLE
Need a mass action to enable/disable multiple periodic tasks at once

### ISSUE THREAD

**Issue by frnhr** [celery/django-celery-beat#12]
This should be simple to do, and also very useful. 

Could the action be a simple ORM call to `queryset.update(...)`, or are there some factors that would complicate it?

![screen_shot_2016-11-25_at_17_59_51](https://cloud.githubusercontent.com/assets/1173748/20631827/312edd34-b339-11e6-9b6b-480e19e73656.jpg)

**Comment by ask** [comment]
The database scheduler implementation uses a separate table to track changes to the schedule: the `PeriodicTasks` model.

The post_save Django signal is used to update the last_update datetime in this table, and when the beat service detects that it has changed it will reload the schedule.

The problem with Django db signals is that they won't trigger when you do `queryset.update` or `queryset.delete`, but this is easily fixed by calling `PeriodicTasks.changed()` after.

**Comment by ask** [comment]
Merged :)
