### ISSUE TITLE
Why is timezone referred to as a field in the docs but its not released?

### ISSUE THREAD

**Issue by viperfx** [celery/django-celery-beat#148]
The current release is 1.1.1, but when you install it, or you take a look at the tag on github, the migration does not involve the timezone field for the 0006 migration file. 

What is going on with this?

**Comment by viiicky** [comment]
yeah, The README is updated as the code is merged to master, but the feature is not released yet. These are the commits made since last release i.e. since v.1.1.1: https://github.com/celery/django-celery-beat/compare/v1.1.1...master

@ask @DDevine @thedrow @ShaheedHaque any idea on the next release date?

I am evaluating django-celery-beat for my scheduling needs and two of the important features will become live in the next release:
- Allow timezone-aware Cron schedules (#99) [397c2c6](https://github.com/celery/django-celery-beat/commit/397c2c6f9d15e4b666dedc90267e8a99018521d2)
- Support Periodic Tasks with a start date and one-off tasks (#78) [27f73a5](https://github.com/celery/django-celery-beat/commit/27f73a565734a2538765723767ed1c96276566e9)

**Comment by thedrow** [comment]
I'll work on a release as soon as I can.

**Comment by viiicky** [comment]
ok, thanks @thedrow

**Comment by devangmehta123** [comment]
Is it safe to use the master branch in our requirements before the next release? We really need the timezone setting feature for the tasks.

We are struggling to get CELERY_TIMEZONE to be recognized as 'Europe/London'. It always works as UTC. 

Our Django is 1.10.2, celery is 4.2.1, django-celery-beat is 1.1.1

I will file separate issue for this.

**Comment by auvipy** [comment]
you can use it

**Comment by thedrow** [comment]
I'm really sorry for the delay.
I've been extremely busy.
Can you please check if 1.2.0 resolves your issue?

**Comment by auvipy** [comment]
Omer, could you also push django-celery-result to pypi?

**Comment by thedrow** [comment]
I'll try to get to it in the next few days.

**Comment by viperfx** [comment]
any updates?

**Comment by viperfx** [comment]
@viiicky what has you done to solve your scheduling needs since your original comment?

**Comment by viiicky** [comment]
@viperfx after testing django-celery-beat quite a lot, I made the decision to not use Celery for our scheduling needs.

We are still using Celery but just for workers. For scheduling purposes, we have put an APScheduler in front.

APScehduler turned out much more mature and reliable for scheduling purposes.

**Comment by viperfx** [comment]
@viiicky thanks for the reply.

Are you using APScheduler with a database backend? E.g. is there tables that maintain a schedule for tasks should fire? does it handle timezones as well?

**Comment by viiicky** [comment]
@viperfx yes we are using database storage for APScehduler.

It maintains a running records of jobs in a table. And the row is present in the DB unless the schedule ends. If the job repeats indefinitely, the row doesn't get deleted ever for that job.

Yes, it has support for Timezones as well. For simplicity, we are using UTC for everything. But nothing stops us from using timezones.

**Comment by viperfx** [comment]
@viiicky okay thanks. That sounds promising.

It sounds like you are scheduling the job programmatically. I am looking to have the schedule or Cron set in a database. 

Do you have an example of how Django models can be setup to use APScheduler?

**Comment by auvipy** [comment]
this should be fixed now
