### ISSUE TITLE
Can I specify task id on creating PeriodicTask?

### ISSUE THREAD

**Issue by zhaoxin** [celery/django-celery-beat#252]
With apply_async I could make a task id, e.g. uuid, in advance and give it to the task I invoke. Can I do this with PeriodicTask.objects.create()? Or with django_celery_beat the task_id only can be given when invoked by this library?
Thanks.

**Comment by liquidpele** [comment]
Task ID is unique for each run, it wouldn't make sense for a periodic task which by definition runs multiple times on a schedule.

**Comment by SebastianDix** [comment]
> Task ID is unique for each run, it wouldn't make sense for a periodic task which by definition runs multiple times on a schedule.

The PeriodicTask can be run as a one-off task e.g. "Execute this in 3 hours and never again" and in that case it would make sense to  set the task_id, or not? It would be nice to know it advance the task_id which will be used for tracking purposes. Otherwise to associate all tasks related to some widget, we basically need to communicate the task_id of the scheduled task only once it has been scheduled.
