### ISSUE TITLE
setup.py does not pull in Django or Celery as direct runtime dependencies

### ISSUE THREAD

**Issue by hartwork** [celery/django-celery-beat#258]
Hi!

I noticed that `setup.py` uses `requirements/*.txt` for dependencies, but none of the ones used during `pip install django-celery-beat` pull in Django and/or Celery, directly. (Django is pulled in indirectly, though). Is that a conscious decision? If not, can they be added?

Best, Sebastian

**Comment by liquidpele** [comment]
Ah, that's probably due to me moving the celery requirement into the python2/python3 requirements files since the supported celery version depends on the python version.   setup.py likely needs to pick one of those depending on the version pip is running with.  I can fix after a while, or if you have time you can send us a PR and I can merge it in.

**Comment by hartwork** [comment]
Can be closed, either now or after next release (due to merge of #258).
