### ISSUE TITLE
Any chance to get unreleased commits into a new release 1.6.0?

### ISSUE THREAD

**Issue by moseb** [celery/django-celery-beat#284]
There's a few commits since 1.5.0 that have not made their way into a release yet:
https://github.com/celery/django-celery-beat/compare/1.5.0...master

Are there plans for a release?

Thanks!

**Comment by auvipy** [comment]
yes by the end of this month

**Comment by robvdl** [comment]
the last released version is 1.4.0 not 1.5.0, still waiting for 1.5.0 to get  released to pypi

**Comment by robvdl** [comment]
sorry I was wrong, the last released docs are 1.4.0, the last released pypi version is 1.5.0, why are the docs not published for rtd for 1.5.0?

**Comment by robvdl** [comment]
@auvipy what's new in 1.6.0 and did 1.5.0 fix the broken migration 2 issue?

I want to upgrade from 1.0.1 but still have horror stories about the broken migration 2 unable to roll back migrations problem, when I upgraded from 1.0.1 to 1.4.0 and had to go back last year due to unforsees circumstances. Reverting the migrations would thrown an exception and leave the db in a bad state.

About a year ago there was some talk about people trying to fix migration 2 but I don't see anything specific about it in the 1.5.0 release notes. It was broken in 1.4.0 even though the release notes for 1.4.0 states it fixes something to do migrations it was actually that particular release that broke them as I recall.

Then after 1.5.0, nothing stating the migrations were fixed in the release notes. I am now confused which release fixed them.

**Comment by moseb** [comment]
@robvdl this kind of unspecific fear post doesn't help anyone: Please do research and open bugs for anything broken.

You can use `git difftool --dir-diff` to compare two Git references regarding their migrations. Commit 786290cb8aab5ec4accef9fcecf7e803b98a5ff2 that went into 1.5.0 might also be of interest.

**Comment by justmobilize** [comment]
@robvdl the project owners worked really hard at fixing the migrations and from my testing everything is good. I too am looking forward to the next release!

**Comment by robvdl** [comment]
Yeah fair enough, I think because it was missed in the 1.5.0 release notes. From what I've seen it was fixed in 1.5.0 but I missed it as it wasn't in the release notes. Thanks, I'll have a go at upgrading these projects next week.

**Comment by shadchin** [comment]
Are there plans for a release?

**Comment by auvipy** [comment]
I am ging to release today

**Comment by moseb** [comment]
> I am ging to release today

Any news?

PS: I'm not sure why https://github.com/celery/django-celery-beat/releases/tag/1.5.0 says "auvipy released this 7 days ago". I thought it was of 2019-05-21.

**Comment by shadchin** [comment]
Any news?

**Comment by auvipy** [comment]
expect one very soon.

**Comment by auvipy** [comment]
done. I would appreciate your donations for working on celery project.
