### ISSUE TITLE
Received unregistered task of type

### ISSUE THREAD

**Issue by aryan9600** [celery/django-celery-beat#366]
### Summary:
I keep getting the following error
```
[2020-10-08 02:24:26,686: ERROR/MainProcess] Received unregistered task of type 'proj.game.tasks.increase_user_xp'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?
```

* Celery Version: 4.4.7
* Celery-Beat Version: 2.0.0

### Detailed information

I have the following project setup:

```
proj/proj/celery.py

import os
from celery import Celery

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'proj.settings')

app = Celery('proj')
app.config_from_object('django.conf:settings', namespace='CELERY')
app.autodiscover_tasks()
```

```
proj/settings.py

CELERY_BROKER_URL = "redis://localhost:6379"
```

```
proj/game/views.py

    def post(self , *args , **kwargs):
        if self.request.user.no_of_attempts == 0:
            schedule, _ = IntervalSchedule.objects.get_or_create(
                every=10, period=IntervalSchedule.SECONDS
            )
            PeriodicTask.objects.create(
                    interval=schedule, name=f"XP Gen for user {self.request.user.id}",
                    task='proj.game.tasks.increase_user_xp',
                    kwargs=json.dumps({'user_id': self.request.user.id})
            )

```

```
proj/game/tasks.py

@shared_task
def increase_user_xp(**kwargs):
    user_id = kwargs.get('user_id', None)
    if user_id:
        user = User.objects.get(id=user_id)
        old_xp = user.xp
        new_xp = old_xp + 10
        return new_xp
```

Any idea what I might be doing wrong?

**Comment by slado122** [comment]
Did you manage to find a solution?

**Comment by auvipy** [comment]
I think you should solve this by following https://stackoverflow.com/questions/9769496/celery-received-unregistered-task-of-type-run-example?page=1&tab=votes#tab-top let me know if anything else happend

**Comment by ChetSocio** [comment]
Naah that doesnot solve the problem as of latest celery and django 4.2 .  Problem occurs when we run celery worker and celery beat command together. When celery beat tries to run scheduled task, the celery worker doesn't recognize the task function and throws error.   
Remember:  normally same task function works fine if its gets triggered as a background task by celery worker.
Once we run celery beat command and celery beat and in time, celery beat triggers the task, we get this error.  The problem is that celery fails it silently on beat terminal and we see the task completed on beat side but we see error on worker side.
