### ISSUE TITLE
Todo: Add warnings about django-celery-beat instability/lack of production readiness to celery documentation

### ISSUE THREAD

**Issue by eskhool** [celery/django-celery-beat#61]
As much as I support, understand and use all things open source ...I cannot endorse pre-alpha code not being called out as such. 

With Celery 4.0.2 being out as a stable release, it is the least that the documentation could do to call out the fact that the django celery beat is nowhere being ready for production use. So creating this ticket so others may be warned, get support for getting documentation updated with the same.

Have already been bitten by over a half dozen issues here. Its come to the point where I am reading the issues to find out if I am about to be bitten by more 👎 👎 👎 !

Have loved celery and djcelery otherwise but this is such a poor replacement and that too as an official contrib

**Comment by DDevine** [comment]
Although eskhool's delivery could be a little more diplomatic, the message is absolutely correct. 

Being honest about alpha/beta grade areas of celery/django-celery-beat is preferable and leaves a **much** better impression than being stung and severely inconvenienced. Although estimating time required for development is often a fools errand, we can at least help give an indication of the risk involved.

We can discuss which parts are sketchy (scheduling, solar and crontab for one - though a couple of us have managed to make it work now at least) here and then submit pull requests for warning notes in the docs? Patches welcome? 

I know commit and PyPI access for two new team members is being addressed (thanks @thedrow and @auvipy), so lets get on top of things like this while the energy is high.

**Comment by auvipy** [comment]
celery is completely a volunteer driven project and we all work on our available times for free. there are so many priority for us to deal with in celery project. If we could afford a full time maintainer fellow like django fellowship program then there could be more possibilities of quality software through better testing.

**Comment by auvipy** [comment]
rather then complaining report issues and fixes if possible

**Comment by DDevine** [comment]
@auvipy the succinct way to say that is to simply say: "Patches welcome" ;)

In the Celery documentation there is some indication given that parts of Celery are "experimental" (see http://docs.celeryproject.org/en/latest/getting-started/brokers/index.html). Perhaps django-celery-beat should do the same.

I think we could either do a feature-list matrix that lists stable, experimental and deprecated features (as shown in the above link) or have in-line documentation warning boxes (highlighted red). 

So the question is - which way should it be done? I am partial to a box like in the above link so that people can get an overview quickly when assessing the suitability of the package for their project, and it may be easier to maintain too.

In general, yes it is *much* better to report an issue and/or provide a fix (as I have done, however all of them are waiting to be merged) rather than complain. **I think @eskhool intended this to be a feature request** in the vein of "Add warnings about unstable features to the documentation" but muddied the waters a bit by expressing disappointment at the current state.

**Comment by auvipy** [comment]
@eskhool http://docs.celeryproject.org/en/master/contributing.html#community-code-of-conduct

**Comment by eskhool** [comment]
@DDevine you are right on the dot. Yes I could have been more politically correct in my delivery but I don't think I am asking for much when I say that django-celery-beat should have been indicated as experimental. 

Running an open source project has great appreciation but it comes with great responsibility and the most basic of that is to just inform if something is known to be of low quality. I am sure the lack of testing would be known to the core devs ( I am assuming @auvipy is one of them). 

@auvipy, I don't think I broke any rules of the code of conduct. I have neither disparaged anyone individually nor been inconsiderate.

I know typically patches are welcome and they will be coming.

**Comment by auvipy** [comment]
closing for now. as many instabilities are fixed now. more actionable reports are welcome.
