### ISSUE TITLE
PyPy solar support 

### ISSUE THREAD

**Issue by DDevine** [celery/django-celery-beat#69]
I notice that now ephem has been added to the tests to support solar schedules, the PyPy test environments are failing because PyPy does not support the C backed for PyEphem and so the dependency cannot be installed.

How should this be handled? I think we need to exclude solar from the PyPy tests and make a note in the documentation about PyPy support. However, this sort of decision is above my pay grade.

**Comment by AlexBohdan** [comment]
Hello @DDevine,

Did you solve this problem?

**Comment by DDevine** [comment]
No sorry I haven't had the time.

**Comment by mbaechtold** [comment]
@DDevine's observation only applies to `pypy3`. 

`PyEphem` is still compatible with `pypy2`, see https://travis-ci.org/celery/django-celery-beat/builds/331458588

**Comment by hohenstaufen** [comment]
Has anyone found a workaround for this? Latest Django release (Django 2) now supports only python3 (that would mean pypy3).

**Comment by eskhool** [comment]
Python3 (pypy3) is not avoidable as it is the future and everyone including django is headed there. Any django project and django-celery-beat is certainly one, needs to head in that direction too.

Since solar schedules are not automatically needed by all of us (may I say many of us?) it should be an optional dependency with try catch for import checks instead of mandating it and hence making pypy unavailable to our entire projects. 

Will a patch towards this approach be accepted?

**Comment by DDevine** [comment]
No, because PyPy and Python 3 are *not* the same thing. PyPy is an (alternative) Python implementation for the Python language. The "default"/reference implementation of Python is called CPython and is written in C.  Solar support relies on some C code written for CPython.

PyPy: https://pypy.org

**Comment by eskhool** [comment]
IMHO, since solar support (hence ephem) is not a critical component for Celery Beat operation for many a use case it should be an optional install like celery[redis] is an option. It is only used by those that need solar support.

It has nothing to do with PyPy. It just shouldn't be a requirement for getting celery-beat to work. (Admittedly I didn't notice it earlier because ephem got installed with all the other crud dependencies which shouldn't be forced into pypi packages).

Anyways, if there is a difference of opinion on this, we have had to fork celery-beat to work around  some bugs that hit us when celery split it into a separate package. Making ephem optional for can survive there just fine. 

If someone else likes this approaches, can reach out via this thread and can pull from us (we haven't published our changes yet)

**Comment by MRigal** [comment]
I think this issue can be marked a solved since 5.1 @auvipy @thedrow
