### ISSUE TITLE
tasks not sent after celery update from 4.02 to 4.1.0

### ISSUE THREAD

**Issue by roy-** [celery/django-celery-beat#70]
tasks not sent after celery update from 4.02 to 4.1.0,

**Comment by razerraz** [comment]
Works for me for crontab, tasks get added/disabled/removed/updated flawlessly without restarting (thanks for all involved at resolving [this issue](https://github.com/celery/django-celery-beat/issues/7#issuecomment-316751392) )

Doesn't work at all for tasks with intervals, even with restarting. The task is run one time and then nothing.

Celery 4.1.0
Django celery beat from git
Don't forget to run the django-celery_beat migrations in your project

**Comment by razerraz** [comment]
I have done further investigations
First, I noticed a bug in celery 4.1.0 when use_tz is true, and with same timezone for django and celery : apply_async method stopped working because of bad ETA due to tz. [This bug is pointed by DDevine with commit here](https://github.com/celery/celery/pull/4173). 
Next, I install celery from git repo to have last commits, including this one. After that, nothing works, even after restarting beat process. I tried this git and [the DDevine one](https://github.com/DDevine/django-celery-beat) : same behaviour -> tasks added before update are running, new ones aren't even after restart. Old tasks stop working after editing them.
I can try further tests if you tell me what to look for

**Comment by DDevine** [comment]
You must use the latest Celery too. There's a lot of inter-dependent behaviour. 
Thanks for looking into this!

**Comment by auvipy** [comment]
sure

**Comment by thedrow** [comment]
I'm assuming this is fixed with the new release. Please correct me if I'm wrong.
